# Generated by Django 5.2.6 on 2025-09-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_attendance_id_alter_attendance_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='email',
            field=models.CharField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
