# Generated by Django 5.2.6 on 2025-09-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_person"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
