# Generated by Django 5.2.6 on 2025-09-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_person"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="created_by",
            new_name="email",
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("email", "date")},
        ),
    ]
