# Generated by Django 5.2.6 on 2025-09-13 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_attendance_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
