# Generated by Django 5.2.6 on 2025-09-13 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_leave'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leave',
            name='unique_leave_per_period',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='id',
        ),
        migrations.AlterField(
            model_name='leave',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
