services:
  - type: web
    name: supabase-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn hrms.wsgi"
    envVars:
      - key: SUPABASE_DB
        sync: false
      - key: SUPABASE_USER
        sync: false
      - key: SUPABASE_PASSWORD
        sync: false
      - key: SUPABASE_HOST
        sync: false
      - key: SUPABASE_PORT
        value: 5432
